name: Wooting

on: push

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Clone
        uses: actions/checkout@v3

      - name: Publish
        run: dotnet publish -c Release -r win-x64 -p:PublishSingleFile=true --self-contained true src/RazerSdkReader.Wooting/RazerSdkReader.Wooting.csproj

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: Wooting
          path: src/RazerSdkReader.Wooting/bin/Release/net7.0/win-x64/publish
